name: Build and Push Docker Image

on:
  push:
    branches: [ main ]

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Determine Version
        run: |
          # We'll use GITHUB_RUN_NUMBER as the patch version
          PATCH_VERSION=${GITHUB_RUN_NUMBER}
          IMAGE_TAG="1.0.${PATCH_VERSION}"
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV

      - name: Build and push image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/my-webapp:${IMAGE_TAG} .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/my-webapp:${IMAGE_TAG}
