name: Build and Push Docker Image

on:
  push:
    branches: [ main ]

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build and push image
        run: |
          IMAGE_TAG=$(date +%Y%m%d%H%M%S) # or use git SHA or semantic version
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/my-webapp:${IMAGE_TAG} .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/my-webapp:${IMAGE_TAG}
          
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV
